// Contract API-surface drift guard. Reads the built `dist/index.d.ts` (the
// published type surface — declarations only, no bodies), normalises it and
// compares against the committed snapshot in `src/contract/index.api.md`.
//
//   node scripts/check-api.mjs check    fail if the surface changed
//   node scripts/check-api.mjs update    record the current surface
//
// The two axes never reconcile on their own: the npm/tag version bumps on every
// release, but the contract SHAPE version (`HOST_API_VERSION`) must move by hand
// only when the shape changes. This guard makes that manual bump non-optional —
// the surface cannot change (or be recorded) while `HOST_API_VERSION` stays put.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const DTS = resolve(here, "../dist/index.d.ts");
const SNAP = resolve(here, "../src/contract/index.api.md");
const SEMVER = /(\d+\.\d+\.\d+)/;

function normalize(dts) {
  let s = dts
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^[ \t]*\/\/.*$/gm, "");
  const m = s.match(/HOST_API_VERSION:\s*"(\d+\.\d+\.\d+)"/);
  s = s.replace(/(HOST_API_VERSION:\s*)"\d+\.\d+\.\d+"/, '$1"<VERSION>"');
  const surface = s
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/, ""))
    .filter((l) => l.trim() !== "")
    .join("\n")
    .trim();
  return { version: m ? m[1] : null, surface: surface + "\n" };
}

function currentSurface() {
  if (!existsSync(DTS)) {
    console.error(`[api] ${DTS} not found — run \`pnpm run build\` first.`);
    process.exit(2);
  }
  return normalize(readFileSync(DTS, "utf8"));
}

function readSnapshot() {
  if (!existsSync(SNAP)) return null;
  const raw = readFileSync(SNAP, "utf8");
  const vm = raw.match(/HOST_API_VERSION:\s*(\d+\.\d+\.\d+)/);
  const cb = raw.match(/```ts\n([\s\S]*?)```/);
  return { version: vm ? vm[1].match(SEMVER)[1] : null, surface: cb ? cb[1] : "" };
}

function render({ version, surface }) {
  return (
    "<!-- Generated by `pnpm run api:update`. Do not edit by hand. -->\n" +
    "# Contract API surface\n\n" +
    "A committed snapshot of the public `@deck-shelves/host` type surface (from\n" +
    "`dist/index.d.ts`, with the version literal neutralised). `pnpm run api:check`\n" +
    "fails when this surface changes without a `HOST_API_VERSION` bump, so an\n" +
    "additive or breaking contract change can never ship while the compatibility\n" +
    "version stays put. After an intended shape change: bump `HOST_API_VERSION`,\n" +
    "then run `pnpm run api:update` and commit this file.\n\n" +
    `HOST_API_VERSION: ${version}\n\n` +
    "```ts\n" +
    surface +
    "```\n"
  );
}

const driftMsg = (v) =>
  `[api] DRIFT: the contract SHAPE changed but HOST_API_VERSION is still ${v}.\n` +
  `[api] Bump it in src/contract/index.ts (additive → MINOR, breaking → MAJOR), then \`pnpm run api:update\`.`;

const mode = process.argv[2] === "update" ? "update" : "check";
const cur = currentSurface();
const snap = readSnapshot();

if (mode === "update") {
  if (snap && cur.surface !== snap.surface && cur.version === snap.version) {
    console.error(driftMsg(cur.version));
    process.exit(1);
  }
  writeFileSync(SNAP, render(cur));
  console.log(`[api] Recorded surface at HOST_API_VERSION ${cur.version}.`);
  process.exit(0);
}

if (!snap) {
  console.error(`[api] No snapshot at ${SNAP}. Run \`pnpm run api:update\` to create it.`);
  process.exit(1);
}
if (cur.surface === snap.surface) {
  console.log(`[api] Surface unchanged (HOST_API_VERSION ${cur.version}).`);
  process.exit(0);
}
if (cur.version === snap.version) {
  console.error(driftMsg(cur.version));
  process.exit(1);
}
console.error(
  `[api] The contract SHAPE changed (${snap.version} → ${cur.version}). ` +
    "Review the diff and run `pnpm run api:update` to record it.",
);
process.exit(1);
